# Generated by Django 5.1.6 on 2026-04-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0014_add_terms_accepted_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='brand_assets',
            field=models.JSONField(blank=True, default=dict, help_text='Logo URL, email, phone, etc.'),
        ),
        migrations.AddField(
            model_name='client',
            name='brand_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='brand_tone',
            field=models.CharField(blank=True, choices=[('professional', 'Professional'), ('casual', 'Casual'), ('funny', 'Funny'), ('inspirational', 'Inspirational'), ('urgent', 'Urgent'), ('friendly', 'Friendly')], max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='business_category',
            field=models.CharField(blank=True, help_text='e.g., Electronics, Retail, Services', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='business_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='business_subcategories',
            field=models.JSONField(blank=True, default=list, help_text='List of subcategories'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('unspecified', 'Unspecified')], max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='gmb_url',
            field=models.URLField(blank=True, help_text='Google My Business profile URL'),
        ),
        migrations.AddField(
            model_name='client',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='product_images',
            field=models.JSONField(blank=True, default=list, help_text='List of product image URLs'),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='client',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='client',
            name='target_locations',
            field=models.JSONField(blank=True, default=list, help_text='List of target countries/cities'),
        ),
        migrations.AddField(
            model_name='client',
            name='usp',
            field=models.TextField(blank=True, help_text='Unique Selling Points'),
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Dict of platform -> URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='social_stats.client')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
