# Generated by Django 5.1.6 on 2026-04-03 19:15

import datetime
from django.db import migrations, models


def seed_site_content(apps, schema_editor):
    SiteContent = apps.get_model('social_stats', 'SiteContent')

    SiteContent.objects.update_or_create(
        key='privacy-policy',
        defaults={
            'title': 'Privacy Policy',
            'effective_date': datetime.date(2026, 4, 3),
            'last_updated': datetime.date(2026, 4, 3),
            'is_public': True,
            'content': {
                'footer_link_label': 'Terms of Service',
                'footer_link_url': '/terms',
                'sections': [
                    {
                        'title': '1. Introduction',
                        'html': '<p>Social State ("we", "our", or "us") operates a social media analytics platform that connects to Facebook, Instagram, Google, YouTube, and LinkedIn to display performance statistics for your social media accounts. We are committed to protecting your privacy. This Privacy Policy explains what data we collect, how we use it, and your rights.</p>',
                    },
                    {
                        'title': '2. Data We Collect',
                        'html': '<p>We collect only the data necessary to provide analytics. This includes:</p><ul><li><strong>Account identifiers</strong> — page IDs, channel IDs, and profile IDs from connected accounts</li><li><strong>Performance metrics</strong> — reach, impressions, likes, comments, shares, follower counts, and engagement rates</li><li><strong>Post data</strong> — post content, published timestamps, and per-post metrics</li><li><strong>Basic profile info</strong> — name and profile picture of connected pages/accounts</li><li><strong>Authentication tokens</strong> — OAuth access tokens and refresh tokens to fetch data on your behalf</li></ul><p>We do <strong>not</strong> collect passwords, private messages, or any data unrelated to analytics.</p>',
                    },
                    {
                        'title': '3. How We Use Your Data',
                        'html': '<ul><li>Display analytics dashboards and reports for your connected accounts</li><li>Sync performance data on a scheduled basis so your stats stay current</li><li>Generate insights and recommendations based on your performance trends</li><li>Send reports to email addresses you provide</li></ul><p>We do <strong>not</strong> sell, rent, or share your data with third parties for advertising or marketing purposes.</p>',
                    },
                    {
                        'title': '4. Facebook & Instagram Data',
                        'html': '<p>We access Facebook and Instagram data through the Meta Graph API under your explicit authorization. We request only the permissions required to read page/account analytics (e.g. <code>pages_read_engagement</code>, <code>instagram_basic</code>, <code>instagram_manage_insights</code>).</p><p>Data obtained from Meta APIs is used solely to display statistics within Social State. We comply with the <a href="https://developers.facebook.com/policy/" target="_blank" rel="noreferrer">Meta Platform Terms</a> and <a href="https://developers.facebook.com/devpolicy/" target="_blank" rel="noreferrer">Meta Developer Policies</a>.</p>',
                    },
                    {
                        'title': '5. Google & YouTube Data',
                        'html': '<p>We access Google and YouTube data through the Google APIs under your explicit authorization. We request only scopes required for reading analytics (e.g. <code>youtube.readonly</code>, <code>yt-analytics.readonly</code>).</p><p>Our use of data received from Google APIs complies with the <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer">Google API Services User Data Policy</a>, including the Limited Use requirements.</p>',
                    },
                    {
                        'title': '6. LinkedIn Data',
                        'html': '<p>We access LinkedIn data through the LinkedIn Marketing API under your explicit authorization. We request only scopes required to read page and post analytics.</p><p>We comply with <a href="https://legal.linkedin.com/api-terms-of-use" target="_blank" rel="noreferrer">LinkedIn API Terms of Use</a>.</p>',
                    },
                    {
                        'title': '7. Data Retention',
                        'html': '<ul><li>Analytics data is retained for as long as you maintain an active account</li><li>OAuth tokens are securely stored and refreshed automatically</li><li>You can request deletion of all your data at any time by contacting us</li><li>Upon account deletion, all associated data is permanently removed within 30 days</li></ul>',
                    },
                    {
                        'title': '8. Data Security',
                        'html': '<p>We use industry-standard security practices including encrypted storage for tokens, HTTPS for all data transmission, and restricted access controls. No system is 100% secure, but we take reasonable measures to protect your information.</p>',
                    },
                    {
                        'title': '9. Your Rights',
                        'html': '<ul><li><strong>Access</strong> — request a copy of the data we hold about you</li><li><strong>Correction</strong> — request corrections to inaccurate data</li><li><strong>Deletion</strong> — request deletion of your account and all associated data</li><li><strong>Revoke access</strong> — disconnect any social account at any time from Settings</li></ul>',
                    },
                    {
                        'title': '10. Contact Us',
                        'html': '<p>For privacy-related questions or requests, contact us at:</p><p><strong>Email:</strong> support@socialstate.ai<br /><strong>Website:</strong> https://socialstate.ai</p>',
                    },
                ],
            },
        },
    )

    SiteContent.objects.update_or_create(
        key='terms-of-service',
        defaults={
            'title': 'Terms of Service',
            'effective_date': datetime.date(2026, 4, 3),
            'last_updated': datetime.date(2026, 4, 3),
            'is_public': True,
            'content': {
                'footer_link_label': 'Privacy Policy',
                'footer_link_url': '/privacy',
                'sections': [
                    {'title': '1. Acceptance of Terms', 'html': '<p>By accessing or using Social State ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service. We may update these terms at any time; continued use of the Service constitutes acceptance of any changes.</p>'},
                    {'title': '2. Description of Service', 'html': '<p>Social State is a social media analytics platform that connects to your Facebook, Instagram, Google, YouTube, and LinkedIn accounts — with your permission — and displays performance statistics, engagement metrics, and post analytics in a unified dashboard.</p><p>We are a <strong>read-only</strong> service. We do not post, publish, delete, or modify any content on your social media accounts.</p>'},
                    {'title': '3. Account Registration', 'html': '<ul><li>You must provide accurate and complete registration information</li><li>You are responsible for maintaining the confidentiality of your login credentials</li><li>You must be at least 18 years old to use the Service</li><li>One person or entity may not maintain more than one free account</li></ul>'},
                    {'title': '4. Connecting Social Accounts', 'html': '<p>When you connect a Facebook, Instagram, Google, YouTube, or LinkedIn account, you authorize Social State to access that account&apos;s analytics data via the respective platform&apos;s official API. You can revoke this access at any time from:</p><ul><li><strong>Facebook/Instagram</strong> — Facebook Settings → Apps and Websites</li><li><strong>Google/YouTube</strong> — Google Account → Security → Third-party access</li><li><strong>LinkedIn</strong> — LinkedIn Settings → Data Privacy → Permitted Services</li><li><strong>Social State</strong> — Settings page within the dashboard</li></ul>'},
                    {'title': '5. Acceptable Use', 'html': '<p>You agree not to:</p><ul><li>Use the Service for any unlawful purpose</li><li>Attempt to reverse-engineer, scrape, or extract data from the Service</li><li>Share your account credentials with unauthorized parties</li><li>Use the Service to violate the terms of any connected social media platform</li><li>Interfere with or disrupt the Service infrastructure</li></ul>'},
                    {'title': '6. Data and Privacy', 'html': '<p>Your use of the Service is also governed by our <a href="/privacy">Privacy Policy</a>, which is incorporated into these Terms by reference. We handle your data in compliance with applicable privacy laws and the data policies of Meta, Google, and LinkedIn.</p>'},
                    {'title': '7. Third-Party Platform Compliance', 'html': '<p>By using Social State, you acknowledge that:</p><ul><li>Your use of Facebook and Instagram data is subject to the <a href="https://www.facebook.com/terms.php" target="_blank" rel="noreferrer">Facebook Terms of Service</a> and <a href="https://developers.facebook.com/policy/" target="_blank" rel="noreferrer">Meta Platform Terms</a></li><li>Your use of Google and YouTube data is subject to the <a href="https://policies.google.com/terms" target="_blank" rel="noreferrer">Google Terms of Service</a> and <a href="https://www.youtube.com/t/terms" target="_blank" rel="noreferrer">YouTube Terms of Service</a></li><li>Your use of LinkedIn data is subject to the <a href="https://www.linkedin.com/legal/user-agreement" target="_blank" rel="noreferrer">LinkedIn User Agreement</a></li></ul>'},
                    {'title': '8. Intellectual Property', 'html': '<p>The Social State platform, including its design, code, and content, is owned by us and protected by intellectual property laws. You may not copy, reproduce, or distribute any part of the Service without written permission.</p><p>Your social media data remains owned by you and the respective platforms. We claim no ownership over data retrieved from your connected accounts.</p>'},
                    {'title': '9. Disclaimers', 'html': '<p>The Service is provided "as is" without warranties of any kind. We do not guarantee that analytics data is 100% accurate, as it is sourced directly from third-party platform APIs. We are not responsible for discrepancies between our dashboard and the native analytics tools of each platform.</p>'},
                    {'title': '10. Limitation of Liability', 'html': '<p>To the maximum extent permitted by law, Social State shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to loss of data or business interruption.</p>'},
                    {'title': '11. Termination', 'html': '<p>We reserve the right to suspend or terminate accounts that violate these Terms. You may delete your account at any time from the Settings page. Upon termination, your data will be deleted within 30 days.</p>'},
                    {'title': '12. Contact Us', 'html': '<p>For questions about these Terms, contact us at:</p><p><strong>Email:</strong> support@socialstate.ai<br /><strong>Website:</strong> https://socialstate.ai</p>'},
                ],
            },
        },
    )


def unseed_site_content(apps, schema_editor):
    SiteContent = apps.get_model('social_stats', 'SiteContent')
    SiteContent.objects.filter(key__in=['privacy-policy', 'terms-of-service']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0017_gmb_models_and_extended_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
                'verbose_name_plural': 'Site Content',
                'ordering': ['key'],
            },
        ),
        migrations.RunPython(seed_site_content, unseed_site_content),
    ]
