# Generated by Django 4.2.9 on 2026-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0029_fix_terms_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmetric',
            name='post_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postmetric',
            name='thumbnail_url',
            field=models.TextField(blank=True),
        ),
    ]
