# Generated by Django 4.2.9 on 2026-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0062_account_lifecycle_notif_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtagset',
            name='platform',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], max_length=30),
        ),
    ]
