# Generated by Django 4.2.9 on 2026-08-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0067_client_public_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='social_stat_created_7bdd14_idx',
            old_name='social_stat_created_6a0f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='social_stat_severit_9fb55e_idx',
            old_name='social_stat_severit_0d8c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='social_stat_resolve_0a9b99_idx',
            old_name='social_stat_resolve_91ab3e_idx',
        ),
        migrations.RenameIndex(
            model_name='errorlog',
            new_name='social_stat_excepti_ecd1fd_idx',
            old_name='social_stat_excepti_4f2b1c_idx',
        ),
    ]
