# Generated by Django 4.2.9 on 2026-08-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_stats', '0070_platformcredential_account_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcredential',
            name='account_picture_url',
            field=models.URLField(blank=True, help_text='Page/channel profile image URL from the social platform'),
        ),
    ]
