apiVersion: v1
kind: ConfigMap
metadata:
  name: social-stats-config
  namespace: social-stats
data:
  ALLOWED_HOSTS: "localhost,127.0.0.1,backend,gateway"
  FRONTEND_URL: "http://localhost:3000"
  MEDIA_ROOT: "/data/media"
  STATIC_ROOT: "/data/staticfiles"
  SQLITE_PATH: "/data/db.sqlite3"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/0"
  CHANNEL_LAYERS_REDIS_URL: "redis://redis:6379/1"
  APP_MODE: "dev"
  DEBUG: "True"
  NGINX_MODE: "dev"
  REACT_APP_API_URL: "http://localhost:8000/api"
