import jsPDF from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';
import { format, parseISO } from 'date-fns';
import { PLATFORMS, fmt } from './platforms';

function setSectionTitle(doc, text, y) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(15);
  doc.setTextColor(15, 23, 42);
  doc.text(text, 14, y);
}

function drawPageHeader(doc, title, subtitle) {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 34, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(title, 14, 18);
  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(subtitle, 14, 26);
  }
}

function drawMetricCards(doc, cards, startY) {
  const cardWidth = 43;
  const cardHeight = 20;
  const gap = 4;

  cards.forEach((card, index) => {
    const row = Math.floor(index / 4);
    const col = index % 4;
    const x = 14 + (cardWidth + gap) * col;
    const y = startY + row * (cardHeight + gap);

    doc.setFillColor(248, 250, 252);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(x, y, cardWidth, cardHeight, 3, 3, 'FD');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(card.label.toUpperCase(), x + 3, y + 6);

    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.text(card.value, x + 3, y + 15);
  });

  return startY + Math.ceil(cards.length / 4) * (cardHeight + gap);
}

async function addChartsPage(doc, chartsElementId, subtitle) {
  const chartsEl = document.getElementById(chartsElementId);
  if (!chartsEl) return false;

  doc.addPage();
  drawPageHeader(doc, 'Performance Charts', subtitle);
  setSectionTitle(doc, 'Dashboard Visuals', 48);

  try {
    const canvas = await html2canvas(chartsEl, {
      scale: 1.5,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false,
    });
    const imgData = canvas.toDataURL('image/png');
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - 28;
    const maxHeight = 220;
    let imgWidth = maxWidth;
    let imgHeight = (canvas.height * imgWidth) / canvas.width;

    if (imgHeight > maxHeight) {
      imgHeight = maxHeight;
      imgWidth = (canvas.width * imgHeight) / canvas.height;
    }

    const x = (pageWidth - imgWidth) / 2;
    doc.addImage(imgData, 'PNG', x, 56, imgWidth, imgHeight);
    return true;
  } catch (error) {
    console.warn('Chart capture failed:', error);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text('Charts could not be captured for this export.', 14, 62);
    return true;
  }
}

function addFooter(doc) {
  const pages = doc.internal.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by Social State • Page ${i} of ${pages} • ${format(new Date(), 'dd/MM/yyyy')}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }
}

export async function exportPDF({
  client,
  summary,
  dateRange,
  chartsElementId,
  posts = [],
  timeseries = [],
  connectedPlatforms = [],
}) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const totals = summary?.totals || {};
  const byPlatform = summary?.by_platform || [];
  const pageSubtitle = `${client.company} • ${dateRange.since} to ${dateRange.until}`;

  drawPageHeader(doc, 'Social Media Report', pageSubtitle);

  doc.setTextColor(71, 85, 105);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(
    'Prepared for client sharing. This report summarizes performance, platform mix, charts, and recent post activity.',
    14,
    44
  );

  setSectionTitle(doc, 'Executive Summary', 56);
  const cardEndY = drawMetricCards(doc, [
    { label: 'Impressions', value: fmt(totals.total_impressions) },
    { label: 'Reach', value: fmt(totals.total_reach) },
    { label: 'Clicks', value: fmt(totals.total_clicks) },
    { label: 'Likes', value: fmt(totals.total_likes) },
    { label: 'Video Views', value: fmt(totals.total_video_views) },
    { label: 'Followers', value: fmt(totals.total_followers) },
    { label: 'Website Clicks', value: fmt(totals.total_website_clicks) },
    { label: 'Phone Calls', value: fmt(totals.total_phone_calls) },
  ], 62);

  doc.autoTable({
    startY: cardEndY + 6,
    head: [['Highlights', 'Value']],
    body: [
      ['Connected Platforms', connectedPlatforms.length ? connectedPlatforms.map(key => PLATFORMS[key]?.label || key).join(', ') : 'None connected'],
      ['Total Posts in Report', String(posts.length)],
      ['Date Range', `${dateRange.since} to ${dateRange.until}`],
      ['Trend Points Captured', String(timeseries.length)],
    ],
    theme: 'grid',
    headStyles: { fillColor: [37, 99, 235], textColor: 255 },
    bodyStyles: { textColor: [51, 65, 85] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 10, cellPadding: 4 },
  });

  if (byPlatform.length > 0) {
    setSectionTitle(doc, 'Platform Breakdown', doc.lastAutoTable.finalY + 12);
    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 16,
      head: [['Platform', 'Impressions', 'Reach', 'Clicks', 'Likes', 'Video Views', 'Followers']],
      body: byPlatform.map((platform) => [
        PLATFORMS[platform.platform]?.label || platform.platform,
        fmt(platform.impressions),
        fmt(platform.reach),
        fmt(platform.clicks),
        fmt(platform.likes),
        fmt(platform.video_views),
        fmt(platform.followers),
      ]),
      theme: 'striped',
      headStyles: { fillColor: [15, 23, 42], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 },
      styles: { fontSize: 9, cellPadding: 3.5 },
    });
  }

  await addChartsPage(doc, chartsElementId, pageSubtitle);

  doc.addPage();
  drawPageHeader(doc, 'Recent Posts Report', pageSubtitle);

  if (posts.length > 0) {
    setSectionTitle(doc, 'Recent Post Performance', 48);
    doc.autoTable({
      startY: 54,
      head: [['Post', 'Platform', 'Account', 'Published', 'Impr.', 'Reach', 'Likes', 'Comments']],
      body: posts.slice(0, 12).map((post) => [
        (post.caption || post.title || 'Untitled post').slice(0, 60),
        PLATFORMS[post.platform]?.label || post.platform,
        post.account_name ? `@${post.account_name}` : '—',
        post.published_at ? format(parseISO(post.published_at), 'dd MMM yyyy') : '—',
        fmt(post.impressions),
        fmt(post.reach),
        fmt(post.likes),
        fmt(post.comments),
      ]),
      theme: 'striped',
      headStyles: { fillColor: [99, 102, 241], textColor: 255 },
      alternateRowStyles: { fillColor: [248, 250, 252] },
      margin: { left: 14, right: 14 },
      styles: { fontSize: 8.5, cellPadding: 3.2, overflow: 'linebreak' },
      columnStyles: {
        0: { cellWidth: 55 },
        1: { cellWidth: 28 },
        2: { cellWidth: 24 },
      },
    });
  } else {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.text('No post data was available for this report period.', 14, 58);
  }

  addFooter(doc);

  const safeName = (client.company || 'client').replace(/\s+/g, '_');
  doc.save(`${safeName}_social_report_${dateRange.since}.pdf`);
}
